---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - test
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- gulpfile.js
- textcomplete
